# docker-compose.yml

services:
  db:
    image: postgres # Use a specific version for consistency
    container_name: node_prisma_db
    restart: always
    ports:
      - "5432:5432" # Exposes the DB port to your local machine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
